### ISSUE TITLE
.net core compatible?

### ISSUE THREAD

**Issue by carlosflorencio** [agabani/FluentSiren#1]
Hi,

Is this lib compatible with .net core?

Thanks!

**Comment by agabani** [comment]
As of now, only .NET Framework 4.5 is supported, I'll put in the work to support .NET Core https://github.com/agabani/FluentSiren/issues/2

**Comment by carlosflorencio** [comment]
There are 2 packages.

FluentSiren Package is compatible, does not have any dependency. Right?

FluentSiren.AspNet.WebApi is only compatible with the full .net framework, yes.

**Comment by agabani** [comment]
**FluentSiren**

Package is not compatible with `.NET Core`. Even though there are no dependencies on other packages, it currently targets `.NET Framework 4.5`, therefore cannot be used. To get it compatible with both `.NET Framework` and `.NET Core`, FluentSiren should be migrated to `.NET Standard 1.0` so it can be shared between platforms.

https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/

**FluentSiren.AspNet.WebApi**

Correct package is only compatible with `.NET Framework` and can not be shared with `.NET Core`. My current intention to provide `.NET Core` support is to create a new package with `.NET core` specific implementation.

**Comment by agabani** [comment]
[v0.6.1.2] `FluentSiren` is now compatible with `.NET Core 1.0+` and `.NET Framework 4.5+`
[v0.6.1.2] `FluentSiren.AspNet.WebApi` remains compatible with `.NET Framework 4.5+`
[v0.6.1.2] `FluentSiren.AspNetCore.Mvc` has been added to support `.NET Core 1.0+`

**Comment by carlosflorencio** [comment]
Very nice work, just in time! 😃 

Thanks!
